import Foundation
import XCTest
@testable import BonedustCore

/// `shared/constants.json` is what the Rails service loads so that its plausibility
/// check uses the same numbers as the client (§6). Swift is the source of truth and
/// the file is generated by `make constants`.
///
/// This suite exists to stop the one failure mode that would be invisible until
/// players complained: someone retunes a constant in Swift, ships it, and the server
/// starts rejecting honest payments because it is still scoring slabs with the old
/// numbers. A stale file fails the build instead.
final class SharedConstantsTests: XCTestCase {

    private var repoRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // BonedustCoreTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // BonedustCore
            .deletingLastPathComponent()   // ios
            .deletingLastPathComponent()   // repo root
    }

    private var constantsURL: URL {
        repoRoot.appending(path: "shared/constants.json")
    }

    func testCheckedInConstantsMatchSwift() throws {
        guard FileManager.default.fileExists(atPath: constantsURL.path) else {
            return XCTFail(
                "shared/constants.json is missing. Run `make constants`."
            )
        }
        let data = try Data(contentsOf: constantsURL)
        let onDisk = try JSONDecoder().decode(SharedConstants.self, from: data)
        let live = SharedConstants(tuning: .standard, catalog: .shared)

        XCTAssertEqual(onDisk.schema, live.schema)
        XCTAssertEqual(onDisk.tuning, live.tuning, "tuning drifted. Run `make constants`.")
        XCTAssertEqual(onDisk.installments, live.installments)
        XCTAssertEqual(onDisk.installmentGrowth, live.installmentGrowth)
        XCTAssertEqual(onDisk.tools, live.tools, "tools drifted. Run `make constants`.")
        XCTAssertEqual(
            onDisk.fossils.map(\.id), live.fossils.map(\.id),
            "fossil list drifted. Run `make constants`."
        )
        XCTAssertEqual(onDisk.fossils, live.fossils, "fossil data drifted. Run `make constants`.")
        XCTAssertEqual(onDisk.sites, live.sites, "site data drifted. Run `make constants`.")
    }

    func testConstantsRoundTrip() throws {
        // If encoding and decoding are not symmetric, the server reads something
        // different from what we think we published.
        let live = SharedConstants(tuning: .standard, catalog: .shared)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        let data = try encoder.encode(live)
        let round = try JSONDecoder().decode(SharedConstants.self, from: data)
        XCTAssertEqual(round, live)
    }

    func testConstantsCarryWhatTheServerNeeds() throws {
        let live = SharedConstants(tuning: .standard, catalog: .shared)
        // The server re-derives bone, rock and gem counts from a seed, so it needs the
        // generation inputs and every fossil's shape.
        XCTAssertFalse(live.sites.isEmpty)
        XCTAssertFalse(live.fossils.isEmpty)
        XCTAssertTrue(live.fossils.allSatisfy { $0.shape.spanCells > 0 })
        XCTAssertEqual(live.tuning.layerHardness.count, 4)
        XCTAssertGreaterThan(live.tuning.rockNodulesMax, 0)
    }

    func testLedgerDataIsWellFormed() throws {
        // The milestone ladder is server-side data (docs/CREW_LEDGER.md) but ships in
        // the app too so the milestone track renders offline.
        let url = repoRoot.appending(path: "shared/ledger.json")
        let data = try Data(contentsOf: url)
        let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        let total = json?["totalDebt"] as? Int
        let milestones = json?["milestones"] as? [[String: Any]]
        let boards = json?["leaderboards"] as? [[String: Any]]

        XCTAssertEqual(total, 2_400_000_000)
        XCTAssertEqual(json?["newGamePlusDebt"] as? Int, 6_000_000_000)
        XCTAssertEqual(milestones?.count, 12)
        XCTAssertFalse(boards?.isEmpty ?? true)

        let amounts = milestones?.compactMap { $0["amount"] as? Int } ?? []
        XCTAssertEqual(amounts, amounts.sorted(), "milestone ladder is not ascending")
        XCTAssertEqual(amounts.last, total, "the last milestone must be the payoff")
        XCTAssertEqual(Set(amounts).count, amounts.count, "duplicate milestone amounts")

        // Every rung has to give the crew something, or it is not a milestone.
        for milestone in milestones ?? [] {
            let unlocks = milestone["unlocks"] as? [String] ?? []
            let cosmetics = milestone["cosmetics"] as? [String] ?? []
            XCTAssertFalse(
                unlocks.isEmpty && cosmetics.isEmpty,
                "milestone \(milestone["id"] ?? "?") rewards nothing"
            )
        }

        // The three sites the brief gates on the ledger must be reachable early, not
        // buried in the hundreds of millions.
        let unlockAmounts: [String: Int] = (milestones ?? []).reduce(into: [:]) { out, m in
            guard let amount = m["amount"] as? Int else { return }
            for unlock in m["unlocks"] as? [String] ?? [] { out[unlock] = amount }
        }
        XCTAssertEqual(unlockAmounts["site:hell_creek"], 1_000_000)
        XCTAssertEqual(unlockAmounts["site:night_dig"], 20_000_000)
        XCTAssertNotNil(unlockAmounts["charmpool:vault"])
        XCTAssertNotNil(unlockAmounts["mode:new_game_plus"])
    }
}
